num = int(input ('digite um número para ver sua tabuada:'))
print('-'*12)
print (f'o valor de {num} x {1} = em {num*1}')
print (f'o valor de {num} x {2} = em {num*2}')
print (f'o valor de {num} x {3} = em {num*3}')
print (f'o valor de {num} x {4} = em {num*4}')
print (f'o valor de {num} x {5} = em {num*5}')
print (f'o valor de {num} x {6} = em {num*6}')
print (f'o valor de {num} x {7} = em {num*7}')
print (f'o valor de {num} x {8} = em {num*8}')
print (f'o valor de {num} x {9} = em {num*9}')
print ('-'*12)